# Palette by Yuval Kolodkin-Gal (@yuvalkolodkingal)
mode = "dark"

background = "#221b28"
dark_background = "#19131e"
darker_background = "#110d15"
lighter_background = "#35283e"
foreground = "#eadfec"
dark_foreground = "#ab94b1"
light_foreground = "#cdbad4"
bright_foreground = "#f8eff9"
accent = "#dea4c1"
selection = "#503651"
muted = "#88718f"
red = "#e598a5"
yellow = "#e1c08e"
orange = "#dcab91"
green = "#b8c49f"
cyan = "#a6c8ca"
blue = "#a9b9df"
magenta = "#c6ace0"
brown = "#ab8f85"
bright_red = "#e9a7b2"
bright_yellow = "#e6c99f"
bright_green = "#c3cdad"
bright_cyan = "#b3d0d2"
bright_blue = "#b6c4e4"
bright_magenta = "#cfb8e5"
hyprland_active_border = "#dea4c1"
hyprland_inactive_border = "#88718f"
