# Palette by Yuval Kolodkin-Gal (@yuvalkolodkingal)
mode = "dark"

background = "#172018"
dark_background = "#101710"
darker_background = "#0b110c"
lighter_background = "#273328"
foreground = "#e4e8d8"
dark_foreground = "#91a184"
light_foreground = "#c9d2bd"
bright_foreground = "#f1f4e7"
accent = "#bed784"
selection = "#3b4e31"
muted = "#6f8465"
red = "#e69a8d"
yellow = "#e1c878"
orange = "#dda46b"
green = "#b3cc88"
cyan = "#97c6ae"
blue = "#9cbfc9"
magenta = "#c1abc7"
brown = "#a28467"
bright_red = "#eaa99e"
bright_yellow = "#e6d08c"
bright_green = "#bed49a"
bright_cyan = "#a7cfba"
bright_blue = "#abc9d1"
bright_magenta = "#cab8cf"
hyprland_active_border = "#bed784"
hyprland_inactive_border = "#6f8465"
