# Palette by Yuval Kolodkin-Gal (@yuvalkolodkingal)
mode = "dark"

background = "#241b18"
dark_background = "#1a1311"
darker_background = "#120d0c"
lighter_background = "#382922"
foreground = "#f0e3d4"
dark_foreground = "#b29a88"
light_foreground = "#d8c5b2"
bright_foreground = "#fbefdf"
accent = "#eab278"
selection = "#59402f"
muted = "#997d67"
red = "#ec9986"
yellow = "#e5c18b"
orange = "#eab278"
green = "#b6c091"
cyan = "#9bc6be"
blue = "#a6b8d0"
magenta = "#c8a4ba"
brown = "#b88e70"
bright_red = "#efa898"
bright_yellow = "#e9ca9c"
bright_green = "#c1c9a2"
bright_cyan = "#aacfc8"
bright_blue = "#b3c3d7"
bright_magenta = "#d0b2c4"
hyprland_active_border = "#eab278"
hyprland_inactive_border = "#997d67"
