# Palette by Yuval Kolodkin-Gal (@yuvalkolodkingal)
mode = "dark"

background = "#132124"
dark_background = "#0e191c"
darker_background = "#091214"
lighter_background = "#21343a"
foreground = "#deebe8"
dark_foreground = "#90aaa9"
light_foreground = "#bcd1cc"
bright_foreground = "#edf7f3"
accent = "#b4a5d9"
selection = "#354553"
muted = "#68858b"
red = "#e59c9b"
yellow = "#d7c68d"
orange = "#d9ad84"
green = "#acc7a2"
cyan = "#91c9c7"
blue = "#9ebedb"
magenta = "#b4a5d9"
brown = "#a49180"
bright_red = "#e9abaa"
bright_yellow = "#ddcf9e"
bright_green = "#b8cfb0"
bright_cyan = "#a2d1cf"
bright_blue = "#adc8e0"
bright_magenta = "#bfb2df"
hyprland_active_border = "#b4a5d9"
hyprland_inactive_border = "#68858b"
